#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "src" / "portfolio_qaoa_bench"
OUTPUT_DIR = ROOT / "monolith-full"
OUTPUT_FILE = OUTPUT_DIR / "portfolio_qaoa_bench_monolith.py"

MODULE_ORDER = [
    "constants.py",
    "interfaces.py",
    "logger.py",
    "native.py",
    "results.py",
    "config.py",
    "spin_hamiltonian.py",
    "exact_diagonalization.py",
    "physical_observables.py",
    "parameter_emergence.py",
    "p_layer_geometry.py",
    "phase_maps.py",
    "data.py",
    "qubo.py",
    "landscape.py",
    "simulator.py",
    "objective.py",
    "optimizers.py",
    "reporting.py",
    "plotting.py",
    "pipeline.py",
    "cli.py",
]

FUTURE_IMPORT = "from __future__ import annotations"
INTERNAL_IMPORT_RE = re.compile(r"^\s*from \.[A-Za-z_][A-Za-z0-9_]* import\b")
ALL_RE = re.compile(r"^\s*__all__\s*=")
VERSION_RE = re.compile(r'__version__\s*=\s*"([^"]+)"')


def _read_version() -> str:
    init_text = (PACKAGE_DIR / "__init__.py").read_text()
    match = VERSION_RE.search(init_text)
    if not match:
        raise RuntimeError("Could not find __version__ in src/portfolio_qaoa_bench/__init__.py")
    return match.group(1)


def _ensure_module_order_complete() -> None:
    expected = sorted(path.name for path in PACKAGE_DIR.glob("*.py") if path.name != "__init__.py")
    actual = sorted(MODULE_ORDER)
    if expected != actual:
        missing = sorted(set(expected) - set(actual))
        extra = sorted(set(actual) - set(expected))
        raise RuntimeError(
            "MODULE_ORDER does not match src/portfolio_qaoa_bench/*.py "
            f"(missing={missing}, extra={extra})."
        )


def _skip_multiline_statement(lines: list[str], start: int) -> int:
    balance = 0
    idx = start
    while idx < len(lines):
        line = lines[idx]
        balance += line.count("(") + line.count("[") + line.count("{")
        balance -= line.count(")") + line.count("]") + line.count("}")
        if idx == start and balance <= 0 and not line.rstrip().endswith("\\"):
            return idx + 1
        if balance <= 0 and not line.rstrip().endswith("\\"):
            return idx + 1
        idx += 1
    return idx


def _transform_module(module_name: str, text: str, *, future_already_emitted: bool) -> tuple[str, bool]:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    idx = 0
    emitted_future = future_already_emitted
    while idx < len(lines):
        line = lines[idx]
        if line.strip() == FUTURE_IMPORT:
            if not emitted_future:
                out.append(line)
                emitted_future = True
            idx += 1
            continue
        if INTERNAL_IMPORT_RE.match(line):
            idx = _skip_multiline_statement(lines, idx)
            continue
        if ALL_RE.match(line):
            idx = _skip_multiline_statement(lines, idx)
            continue
        out.append(line)
        idx += 1

    body = "".join(out).strip()
    section = (
        f"# === Begin {module_name} ===\n\n"
        f"{body}\n\n"
        f"# === End {module_name} ===\n"
    )
    return section, emitted_future


def build_monolith() -> str:
    _ensure_module_order_complete()
    version = _read_version()
    sections: list[str] = [
        '"""Generated monolithic mirror of the portfolio_qaoa_bench package.\n\n'
        "Do not edit this file directly. Rebuild it with:\n"
        "    python scripts/build_monolith_full.py\n"
        '"""\n\n',
        "from __future__ import annotations\n\n",
        f'__version__ = "{version}"\n\n',
    ]
    emitted_future = True
    for module_name in MODULE_ORDER:
        text = (PACKAGE_DIR / module_name).read_text()
        section, emitted_future = _transform_module(module_name, text, future_already_emitted=emitted_future)
        sections.append(section)
        sections.append("\n")
    monolith = "".join(sections).rstrip() + "\n"
    compile(monolith, str(OUTPUT_FILE), "exec")
    return monolith


def main() -> int:
    parser = argparse.ArgumentParser(description="Build or verify the generated monolith-full mirror.")
    parser.add_argument("--check", action="store_true", help="Fail if monolith-full is out of date.")
    args = parser.parse_args()

    monolith = build_monolith()
    existing = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else None

    if args.check:
        if existing == monolith:
            print(f"monolith-full is up to date: {OUTPUT_FILE.relative_to(ROOT)}")
            return 0
        before = [] if existing is None else existing.splitlines()
        after = monolith.splitlines()
        diff = difflib.unified_diff(
            before,
            after,
            fromfile="current",
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff))
        print(f"\nmonolith-full is out of date: {OUTPUT_FILE.relative_to(ROOT)}", file=sys.stderr)
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(monolith)
    print(f"wrote {OUTPUT_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
